package entidades;
// Generated 09-28-2015 08:03:09 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Bono generated by hbm2java
 */
public class Bono  implements java.io.Serializable {


     private int idBono;
     private Empleado empleado;
     private Date fecha;
     private int idTipoBono;

    public Bono() {
    }

    public Bono(int idBono, Empleado empleado, Date fecha, int idTipoBono) {
       this.idBono = idBono;
       this.empleado = empleado;
       this.fecha = fecha;
       this.idTipoBono = idTipoBono;
    }
   
    public int getIdBono() {
        return this.idBono;
    }
    
    public void setIdBono(int idBono) {
        this.idBono = idBono;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getIdTipoBono() {
        return this.idTipoBono;
    }
    
    public void setIdTipoBono(int idTipoBono) {
        this.idTipoBono = idTipoBono;
    }




}


