package entidades;
// Generated 09-28-2015 08:03:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private int idDepartamento;
     private String nombre;
     private String descripcion;
     private Set empleados = new HashSet(0);
     private Set objdepartamentos = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(int idDepartamento, String nombre, String descripcion) {
        this.idDepartamento = idDepartamento;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Departamento(int idDepartamento, String nombre, String descripcion, Set empleados, Set objdepartamentos) {
       this.idDepartamento = idDepartamento;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.empleados = empleados;
       this.objdepartamentos = objdepartamentos;
    }
   
    public int getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }
    public Set getObjdepartamentos() {
        return this.objdepartamentos;
    }
    
    public void setObjdepartamentos(Set objdepartamentos) {
        this.objdepartamentos = objdepartamentos;
    }




}


