package entidades;
// Generated 09-28-2015 08:03:09 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Descuento generated by hbm2java
 */
public class Descuento  implements java.io.Serializable {


     private int idDescuento;
     private Empleado empleado;
     private TipoDescuento tipoDescuento;
     private Date fecha;

    public Descuento() {
    }

    public Descuento(int idDescuento, Empleado empleado, TipoDescuento tipoDescuento, Date fecha) {
       this.idDescuento = idDescuento;
       this.empleado = empleado;
       this.tipoDescuento = tipoDescuento;
       this.fecha = fecha;
    }
   
    public int getIdDescuento() {
        return this.idDescuento;
    }
    
    public void setIdDescuento(int idDescuento) {
        this.idDescuento = idDescuento;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public TipoDescuento getTipoDescuento() {
        return this.tipoDescuento;
    }
    
    public void setTipoDescuento(TipoDescuento tipoDescuento) {
        this.tipoDescuento = tipoDescuento;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


