package entidades;
// Generated 10-02-2015 07:45:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int empleadoId;
     private Departamento departamento;
     private PuestoTrabajo puestoTrabajo;
     private String dui;
     private String isss;
     private String afp;
     private String sexo;
     private String nit;
     private String nombre;
     private String apellido;
     private String cuenta;
     private double salario;
     private Integer edad;
     private String estadoCivil;
     private String direccion;
     private Set sancions = new HashSet(0);
     private Set descuentos = new HashSet(0);
     private Set telefonos = new HashSet(0);
     private Set expLaborals = new HashSet(0);
     private Set reconocimientos = new HashSet(0);
     private Set correos = new HashSet(0);
     private Set puestoHistoricos = new HashSet(0);
     private Set vacacions = new HashSet(0);
     private Set bonos = new HashSet(0);
     private Set educacions = new HashSet(0);
     private Set permisos = new HashSet(0);
     private Set transaccions = new HashSet(0);
     private Set evaluacions = new HashSet(0);
     private Set contratos = new HashSet(0);
     private Set capacitacions = new HashSet(0);
     private Set planillas = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(int empleadoId, Departamento departamento, PuestoTrabajo puestoTrabajo, String dui, String isss, String afp, String nit, String nombre, String apellido, String cuenta, double salario, String direccion) {
        this.empleadoId = empleadoId;
        this.departamento = departamento;
        this.puestoTrabajo = puestoTrabajo;
        this.dui = dui;
        this.isss = isss;
        this.afp = afp;
        this.nit = nit;
        this.nombre = nombre;
        this.apellido = apellido;
        this.cuenta = cuenta;
        this.salario = salario;
        this.direccion = direccion;
    }
    public Empleado(int empleadoId, Departamento departamento, PuestoTrabajo puestoTrabajo, String dui, String isss, String afp, String sexo, String nit, String nombre, String apellido, String cuenta, double salario, Integer edad, String estadoCivil, String direccion, Set sancions, Set descuentos, Set telefonos, Set expLaborals, Set reconocimientos, Set correos, Set puestoHistoricos, Set vacacions, Set bonos, Set educacions, Set permisos, Set transaccions, Set evaluacions, Set contratos, Set capacitacions, Set planillas) {
       this.empleadoId = empleadoId;
       this.departamento = departamento;
       this.puestoTrabajo = puestoTrabajo;
       this.dui = dui;
       this.isss = isss;
       this.afp = afp;
       this.sexo = sexo;
       this.nit = nit;
       this.nombre = nombre;
       this.apellido = apellido;
       this.cuenta = cuenta;
       this.salario = salario;
       this.edad = edad;
       this.estadoCivil = estadoCivil;
       this.direccion = direccion;
       this.sancions = sancions;
       this.descuentos = descuentos;
       this.telefonos = telefonos;
       this.expLaborals = expLaborals;
       this.reconocimientos = reconocimientos;
       this.correos = correos;
       this.puestoHistoricos = puestoHistoricos;
       this.vacacions = vacacions;
       this.bonos = bonos;
       this.educacions = educacions;
       this.permisos = permisos;
       this.transaccions = transaccions;
       this.evaluacions = evaluacions;
       this.contratos = contratos;
       this.capacitacions = capacitacions;
       this.planillas = planillas;
    }
   
    public int getEmpleadoId() {
        return this.empleadoId;
    }
    
    public void setEmpleadoId(int empleadoId) {
        this.empleadoId = empleadoId;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public PuestoTrabajo getPuestoTrabajo() {
        return this.puestoTrabajo;
    }
    
    public void setPuestoTrabajo(PuestoTrabajo puestoTrabajo) {
        this.puestoTrabajo = puestoTrabajo;
    }
    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }
    public String getIsss() {
        return this.isss;
    }
    
    public void setIsss(String isss) {
        this.isss = isss;
    }
    public String getAfp() {
        return this.afp;
    }
    
    public void setAfp(String afp) {
        this.afp = afp;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }
    public double getSalario() {
        return this.salario;
    }
    
    public void setSalario(double salario) {
        this.salario = salario;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getSancions() {
        return this.sancions;
    }
    
    public void setSancions(Set sancions) {
        this.sancions = sancions;
    }
    public Set getDescuentos() {
        return this.descuentos;
    }
    
    public void setDescuentos(Set descuentos) {
        this.descuentos = descuentos;
    }
    public Set getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(Set telefonos) {
        this.telefonos = telefonos;
    }
    public Set getExpLaborals() {
        return this.expLaborals;
    }
    
    public void setExpLaborals(Set expLaborals) {
        this.expLaborals = expLaborals;
    }
    public Set getReconocimientos() {
        return this.reconocimientos;
    }
    
    public void setReconocimientos(Set reconocimientos) {
        this.reconocimientos = reconocimientos;
    }
    public Set getCorreos() {
        return this.correos;
    }
    
    public void setCorreos(Set correos) {
        this.correos = correos;
    }
    public Set getPuestoHistoricos() {
        return this.puestoHistoricos;
    }
    
    public void setPuestoHistoricos(Set puestoHistoricos) {
        this.puestoHistoricos = puestoHistoricos;
    }
    public Set getVacacions() {
        return this.vacacions;
    }
    
    public void setVacacions(Set vacacions) {
        this.vacacions = vacacions;
    }
    public Set getBonos() {
        return this.bonos;
    }
    
    public void setBonos(Set bonos) {
        this.bonos = bonos;
    }
    public Set getEducacions() {
        return this.educacions;
    }
    
    public void setEducacions(Set educacions) {
        this.educacions = educacions;
    }
    public Set getPermisos() {
        return this.permisos;
    }
    
    public void setPermisos(Set permisos) {
        this.permisos = permisos;
    }
    public Set getTransaccions() {
        return this.transaccions;
    }
    
    public void setTransaccions(Set transaccions) {
        this.transaccions = transaccions;
    }
    public Set getEvaluacions() {
        return this.evaluacions;
    }
    
    public void setEvaluacions(Set evaluacions) {
        this.evaluacions = evaluacions;
    }
    public Set getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }
    public Set getCapacitacions() {
        return this.capacitacions;
    }
    
    public void setCapacitacions(Set capacitacions) {
        this.capacitacions = capacitacions;
    }
    public Set getPlanillas() {
        return this.planillas;
    }
    
    public void setPlanillas(Set planillas) {
        this.planillas = planillas;
    }




}


