package entidades;
// Generated 09-28-2015 08:03:09 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Evaluacion generated by hbm2java
 */
public class Evaluacion  implements java.io.Serializable {


     private int idEvaluacion;
     private Criterio criterio;
     private Empleado empleado;
     private double puntaje;
     private Date fecha;

    public Evaluacion() {
    }

    public Evaluacion(int idEvaluacion, Criterio criterio, Empleado empleado, double puntaje, Date fecha) {
       this.idEvaluacion = idEvaluacion;
       this.criterio = criterio;
       this.empleado = empleado;
       this.puntaje = puntaje;
       this.fecha = fecha;
    }
   
    public int getIdEvaluacion() {
        return this.idEvaluacion;
    }
    
    public void setIdEvaluacion(int idEvaluacion) {
        this.idEvaluacion = idEvaluacion;
    }
    public Criterio getCriterio() {
        return this.criterio;
    }
    
    public void setCriterio(Criterio criterio) {
        this.criterio = criterio;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public double getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(double puntaje) {
        this.puntaje = puntaje;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


