package entidades;
// Generated 09-28-2015 08:03:09 PM by Hibernate Tools 4.3.1



/**
 * Objdepartamento generated by hbm2java
 */
public class Objdepartamento  implements java.io.Serializable {


     private long idObjetivodep;
     private Departamento departamento;
     private String tipo;
     private String descripcion;
     private Integer idx;

    public Objdepartamento() {
    }

	
    public Objdepartamento(long idObjetivodep) {
        this.idObjetivodep = idObjetivodep;
    }
    public Objdepartamento(long idObjetivodep, Departamento departamento, String tipo, String descripcion, Integer idx) {
       this.idObjetivodep = idObjetivodep;
       this.departamento = departamento;
       this.tipo = tipo;
       this.descripcion = descripcion;
       this.idx = idx;
    }
   
    public long getIdObjetivodep() {
        return this.idObjetivodep;
    }
    
    public void setIdObjetivodep(long idObjetivodep) {
        this.idObjetivodep = idObjetivodep;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getIdx() {
        return this.idx;
    }
    
    public void setIdx(Integer idx) {
        this.idx = idx;
    }




}


