package entidades;
// Generated 09-28-2015 08:03:09 PM by Hibernate Tools 4.3.1



/**
 * Objetivo generated by hbm2java
 */
public class Objetivo  implements java.io.Serializable {


     private int idObjetivo;
     private PuestoTrabajo puestoTrabajo;
     private String funcion;
     private Integer idx;

    public Objetivo() {
    }

	
    public Objetivo(int idObjetivo, String funcion) {
        this.idObjetivo = idObjetivo;
        this.funcion = funcion;
    }
    public Objetivo(int idObjetivo, PuestoTrabajo puestoTrabajo, String funcion, Integer idx) {
       this.idObjetivo = idObjetivo;
       this.puestoTrabajo = puestoTrabajo;
       this.funcion = funcion;
       this.idx = idx;
    }
   
    public int getIdObjetivo() {
        return this.idObjetivo;
    }
    
    public void setIdObjetivo(int idObjetivo) {
        this.idObjetivo = idObjetivo;
    }
    public PuestoTrabajo getPuestoTrabajo() {
        return this.puestoTrabajo;
    }
    
    public void setPuestoTrabajo(PuestoTrabajo puestoTrabajo) {
        this.puestoTrabajo = puestoTrabajo;
    }
    public String getFuncion() {
        return this.funcion;
    }
    
    public void setFuncion(String funcion) {
        this.funcion = funcion;
    }
    public Integer getIdx() {
        return this.idx;
    }
    
    public void setIdx(Integer idx) {
        this.idx = idx;
    }




}


