package entidades;
// Generated 09-28-2015 08:03:09 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Planilla generated by hbm2java
 */
public class Planilla  implements java.io.Serializable {


     private int idPlanilla;
     private Empleado empleado;
     private Date fechaInicio;
     private Date fechaFin;

    public Planilla() {
    }

    public Planilla(int idPlanilla, Empleado empleado, Date fechaInicio, Date fechaFin) {
       this.idPlanilla = idPlanilla;
       this.empleado = empleado;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
    public int getIdPlanilla() {
        return this.idPlanilla;
    }
    
    public void setIdPlanilla(int idPlanilla) {
        this.idPlanilla = idPlanilla;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


