package entidades;
// Generated 09-28-2015 08:03:09 PM by Hibernate Tools 4.3.1



/**
 * Reconocimiento generated by hbm2java
 */
public class Reconocimiento  implements java.io.Serializable {


     private int idReconocimiento;
     private Empleado empleado;
     private String descripcion;

    public Reconocimiento() {
    }

    public Reconocimiento(int idReconocimiento, Empleado empleado, String descripcion) {
       this.idReconocimiento = idReconocimiento;
       this.empleado = empleado;
       this.descripcion = descripcion;
    }
   
    public int getIdReconocimiento() {
        return this.idReconocimiento;
    }
    
    public void setIdReconocimiento(int idReconocimiento) {
        this.idReconocimiento = idReconocimiento;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


