package entidades;
// Generated 09-28-2015 08:03:09 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sancion generated by hbm2java
 */
public class Sancion  implements java.io.Serializable {


     private int idSancion;
     private Empleado empleado;
     private int gravedad;
     private String descripcion;
     private Date fecha;

    public Sancion() {
    }

    public Sancion(int idSancion, Empleado empleado, int gravedad, String descripcion, Date fecha) {
       this.idSancion = idSancion;
       this.empleado = empleado;
       this.gravedad = gravedad;
       this.descripcion = descripcion;
       this.fecha = fecha;
    }
   
    public int getIdSancion() {
        return this.idSancion;
    }
    
    public void setIdSancion(int idSancion) {
        this.idSancion = idSancion;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public int getGravedad() {
        return this.gravedad;
    }
    
    public void setGravedad(int gravedad) {
        this.gravedad = gravedad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


