package entidades;
// Generated 09-28-2015 08:03:09 PM by Hibernate Tools 4.3.1



/**
 * Telefono generated by hbm2java
 */
public class Telefono  implements java.io.Serializable {


     private int idTelefono;
     private Empleado empleado;
     private String telefono;

    public Telefono() {
    }

    public Telefono(int idTelefono, Empleado empleado, String telefono) {
       this.idTelefono = idTelefono;
       this.empleado = empleado;
       this.telefono = telefono;
    }
   
    public int getIdTelefono() {
        return this.idTelefono;
    }
    
    public void setIdTelefono(int idTelefono) {
        this.idTelefono = idTelefono;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


