package entidades;
// Generated 09-28-2015 08:03:09 PM by Hibernate Tools 4.3.1



/**
 * TipoBono generated by hbm2java
 */
public class TipoBono  implements java.io.Serializable {


     private int idTipoBono;
     private PuestoTrabajo puestoTrabajo;
     private double porcentaje;

    public TipoBono() {
    }

    public TipoBono(int idTipoBono, PuestoTrabajo puestoTrabajo, double porcentaje) {
       this.idTipoBono = idTipoBono;
       this.puestoTrabajo = puestoTrabajo;
       this.porcentaje = porcentaje;
    }
   
    public int getIdTipoBono() {
        return this.idTipoBono;
    }
    
    public void setIdTipoBono(int idTipoBono) {
        this.idTipoBono = idTipoBono;
    }
    public PuestoTrabajo getPuestoTrabajo() {
        return this.puestoTrabajo;
    }
    
    public void setPuestoTrabajo(PuestoTrabajo puestoTrabajo) {
        this.puestoTrabajo = puestoTrabajo;
    }
    public double getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(double porcentaje) {
        this.porcentaje = porcentaje;
    }




}


