package entidades;
// Generated 09-28-2015 08:03:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoContrato generated by hbm2java
 */
public class TipoContrato  implements java.io.Serializable {


     private int idTipoContrato;
     private String descripcion;
     private Set contratos = new HashSet(0);

    public TipoContrato() {
    }

	
    public TipoContrato(int idTipoContrato, String descripcion) {
        this.idTipoContrato = idTipoContrato;
        this.descripcion = descripcion;
    }
    public TipoContrato(int idTipoContrato, String descripcion, Set contratos) {
       this.idTipoContrato = idTipoContrato;
       this.descripcion = descripcion;
       this.contratos = contratos;
    }
   
    public int getIdTipoContrato() {
        return this.idTipoContrato;
    }
    
    public void setIdTipoContrato(int idTipoContrato) {
        this.idTipoContrato = idTipoContrato;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }




}


