package entidades;
// Generated 09-28-2015 08:03:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoPermiso generated by hbm2java
 */
public class TipoPermiso  implements java.io.Serializable {


     private int idTipoPermiso;
     private String descripcion;
     private Set permisos = new HashSet(0);

    public TipoPermiso() {
    }

	
    public TipoPermiso(int idTipoPermiso, String descripcion) {
        this.idTipoPermiso = idTipoPermiso;
        this.descripcion = descripcion;
    }
    public TipoPermiso(int idTipoPermiso, String descripcion, Set permisos) {
       this.idTipoPermiso = idTipoPermiso;
       this.descripcion = descripcion;
       this.permisos = permisos;
    }
   
    public int getIdTipoPermiso() {
        return this.idTipoPermiso;
    }
    
    public void setIdTipoPermiso(int idTipoPermiso) {
        this.idTipoPermiso = idTipoPermiso;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getPermisos() {
        return this.permisos;
    }
    
    public void setPermisos(Set permisos) {
        this.permisos = permisos;
    }




}


