package entidades;
// Generated 09-28-2015 08:03:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoDescuento generated by hbm2java
 */
public class TipoDescuento  implements java.io.Serializable {


     private int idTipoDescuento;
     private String descripcion;
     private double porcentaje;
     private Set descuentos = new HashSet(0);

    public TipoDescuento() {
    }

	
    public TipoDescuento(int idTipoDescuento, String descripcion, double porcentaje) {
        this.idTipoDescuento = idTipoDescuento;
        this.descripcion = descripcion;
        this.porcentaje = porcentaje;
    }
    public TipoDescuento(int idTipoDescuento, String descripcion, double porcentaje, Set descuentos) {
       this.idTipoDescuento = idTipoDescuento;
       this.descripcion = descripcion;
       this.porcentaje = porcentaje;
       this.descuentos = descuentos;
    }
   
    public int getIdTipoDescuento() {
        return this.idTipoDescuento;
    }
    
    public void setIdTipoDescuento(int idTipoDescuento) {
        this.idTipoDescuento = idTipoDescuento;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public double getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(double porcentaje) {
        this.porcentaje = porcentaje;
    }
    public Set getDescuentos() {
        return this.descuentos;
    }
    
    public void setDescuentos(Set descuentos) {
        this.descuentos = descuentos;
    }




}


