package entidades;
// Generated 09-28-2015 08:03:09 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Transaccion generated by hbm2java
 */
public class Transaccion  implements java.io.Serializable {


     private int idTransaccion;
     private Empleado empleado;
     private boolean creditoDebito;
     private double monto;
     private Date fecha;

    public Transaccion() {
    }

    public Transaccion(int idTransaccion, Empleado empleado, boolean creditoDebito, double monto, Date fecha) {
       this.idTransaccion = idTransaccion;
       this.empleado = empleado;
       this.creditoDebito = creditoDebito;
       this.monto = monto;
       this.fecha = fecha;
    }
   
    public int getIdTransaccion() {
        return this.idTransaccion;
    }
    
    public void setIdTransaccion(int idTransaccion) {
        this.idTransaccion = idTransaccion;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public boolean isCreditoDebito() {
        return this.creditoDebito;
    }
    
    public void setCreditoDebito(boolean creditoDebito) {
        this.creditoDebito = creditoDebito;
    }
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


