/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package capaPresentacion;

import encapsulacion.cargo;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logicaNegocio.logicaCargo;

/**
 *
 * @author byron
 */
public class admCargo extends javax.swing.JPanel {

      
    crearCargo cc;
    DefaultTableModel tablaCargo;
    infoCargo inf;
    /**
     * Creates new form admCargo
     */
    public admCargo() {
        initComponents();
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableCargos = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        agregarCargo = new javax.swing.JButton();
        modicarCargo = new javax.swing.JButton();
        eliminarCargo = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buscarCargo = new javax.swing.JButton();
        puestoTxt = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jtableCargos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Puesto Trabajo"
            }
        ));
        jtableCargos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableCargosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableCargos);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalles de Puesto Trabajo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("AvantGarde LT Medium", 0, 12))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Administracion de Puestos de Trabajo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("AvantGarde LT Medium", 0, 12))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregarCargo.setText("Agregar");
        agregarCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCargoActionPerformed(evt);
            }
        });
        jPanel1.add(agregarCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        modicarCargo.setText("Modificar ");
        modicarCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modicarCargoActionPerformed(evt);
            }
        });
        jPanel1.add(modicarCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        eliminarCargo.setText("Eliminar");
        eliminarCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCargoActionPerformed(evt);
            }
        });
        jPanel1.add(eliminarCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        jPanel1.add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Puesto de Trabajo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("AvantGarde LT Medium", 0, 12))); // NOI18N

        jLabel2.setText("Puesto de Trabajo:");

        buscarCargo.setText("Buscar");
        buscarCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCargoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(puestoTxt)
                .addGap(18, 18, 18)
                .addComponent(buscarCargo)
                .addGap(36, 36, 36))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(puestoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarCargo))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtableCargosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableCargosMouseClicked
        // TODO add your handling code here:

      tablaCargo=(DefaultTableModel)jtableCargos.getModel();
      inf=new infoCargo();
      String dato;
       int iD;
        jPanel5.removeAll();
        jPanel5.repaint();
        dato=String.valueOf(tablaCargo.getValueAt(jtableCargos.getSelectedRow(),0));
        iD=Integer.parseInt(dato);
        inf.CargarCargo(iD);
        inf.setVisible(true);
        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel5.add(inf);
        jPanel5.revalidate();

    }//GEN-LAST:event_jtableCargosMouseClicked

    private void agregarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCargoActionPerformed
        // TODO add your handling code here:
        cc=new crearCargo();
        cc.setVisible(true);
        cc.pack();
        
    }//GEN-LAST:event_agregarCargoActionPerformed

    private void modicarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modicarCargoActionPerformed
        // TODO add your handling code here:
        /**tablaDepart=(DefaultTableModel)tablaDepartamento.getModel();
        int dato;
        try{

            dato=Integer.parseInt(String.valueOf(tablaDepart.getValueAt(tablaDepartamento.getSelectedRow(),0)));
            depM=new ModificarDepartament();
            depM.setVisible(true);
            depM.pack();
            depM.mostrarDepart(dato);

        }catch(IndexOutOfBoundsException e){

            JOptionPane.showMessageDialog(null,"Seleccione un Departamento","!Error¡",JOptionPane.ERROR_MESSAGE);
        }**/
    }//GEN-LAST:event_modicarCargoActionPerformed

    private void eliminarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCargoActionPerformed
        // TODO add your handling code here:
      /**  int dato;
        tablaDepart=(DefaultTableModel)tablaDepartamento.getModel();
        logicaDepartamento dep=new logicaDepartamento();
        dato=Integer.parseInt(String.valueOf(tablaDepart.getValueAt(tablaDepartamento.getSelectedRow(),0)));
        dep.eliminar(dato);
        **/
    }//GEN-LAST:event_eliminarCargoActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // TODO add your handling code here:
        LimpiarJTable();
        tablaCargo=(DefaultTableModel)jtableCargos.getModel();
        logicaCargo c=new logicaCargo();
        Object [] fila =new Object[2];
        Set<cargo> cargos=null;
        cargos=c.consultar();
        for(cargo ca : cargos)
        {
            fila[0]= ca.getId();
            fila[1]= ca.getNombre();
            tablaCargo.addRow(fila);
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void buscarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCargoActionPerformed
        if(!puestoTxt.getText().isEmpty()){
            // CODIGO BUSQUEDA
        } else
            JOptionPane.showMessageDialog(null,"Ingrese un texto de búsqueda","¡Error!",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_buscarCargoActionPerformed

     private void LimpiarJTable(){
        tablaCargo=(DefaultTableModel)jtableCargos.getModel();
        int a =tablaCargo.getRowCount()-1;
        for(int i=a;i>=0;i--){ 
            tablaCargo.removeRow(i);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton agregarCargo;
    private javax.swing.JButton buscarCargo;
    private javax.swing.JButton eliminarCargo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtableCargos;
    private javax.swing.JButton modicarCargo;
    private javax.swing.JTextField puestoTxt;
    // End of variables declaration//GEN-END:variables
}
