/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package capaPresentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author byron
 */
public class admPlanilla extends javax.swing.JPanel {

    /**
     * Creates new form admPlanilla
     */
    public admPlanilla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboDepto = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmps = new javax.swing.JTable();
        dateTxt = new datechooser.beans.DateChooserCombo();
        btnSave = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        checkRenta = new javax.swing.JCheckBox();
        checkISSS = new javax.swing.JCheckBox();
        checkAFP = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        comboConcepts = new javax.swing.JList();
        applyConcept = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Generar Planilla"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre Planilla:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 43, -1, -1));
        jPanel1.add(nombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 40, 154, -1));

        jLabel2.setText("Fecha de Calculo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 99, -1, -1));

        jLabel4.setText("Departamento:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 154, -1, -1));

        comboDepto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 152, 154, -1));

        jLabel3.setText("Lista de Empleados");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 216, -1, -1));

        tablaEmps.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaEmps);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 249, 437, 184));

        dateTxt.setCalendarPreferredSize(new java.awt.Dimension(222, 159));
        try {
            dateTxt.setDefaultPeriods(new datechooser.model.multiple.PeriodSet());
        } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
            e1.printStackTrace();
        }
        jPanel1.add(dateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 96, 154, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 520, 460));

        btnSave.setText("Guardar y Generar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 519, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Conceptos de Ley"));

        checkRenta.setText("Renta");

        checkISSS.setText("ISSS");

        checkAFP.setText("AFP");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(checkRenta)
                .addGap(46, 46, 46)
                .addComponent(checkISSS)
                .addGap(42, 42, 42)
                .addComponent(checkAFP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkRenta)
                    .addComponent(checkISSS)
                    .addComponent(checkAFP))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 440, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Otro Conceptos"));

        comboConcepts.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(comboConcepts);

        applyConcept.setText("Aplicar Conceptos Seleccionados");
        applyConcept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyConceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(applyConcept)
                .addGap(93, 93, 93))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(applyConcept)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 440, 310));
    }// </editor-fold>//GEN-END:initComponents

    private void applyConceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyConceptActionPerformed
        if(comboConcepts.getSelectedIndex() != -1){
            // APPLY CODE
        } else
            JOptionPane.showMessageDialog(null, "Seleccione al menos 1 concepto a aplicar", "¡Error!", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_applyConceptActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(!nombreTxt.getText().isEmpty() && dateTxt.getSelectedDate() != null && comboDepto.getSelectedIndex() != -1 && 
                (checkRenta.isSelected() || checkISSS.isSelected() || checkAFP.isSelected()) /* VERIFICAR SI ESTOS VALORES SON OLBIGATORIOS */){
            // SAVE CODE
        } else
            JOptionPane.showMessageDialog(null, "Ingrese nombre, fecha cálculo, departamento y al menos 1 concepto de ley", "¡Error!", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyConcept;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox checkAFP;
    private javax.swing.JCheckBox checkISSS;
    private javax.swing.JCheckBox checkRenta;
    private javax.swing.JList comboConcepts;
    private javax.swing.JComboBox comboDepto;
    private datechooser.beans.DateChooserCombo dateTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTable tablaEmps;
    // End of variables declaration//GEN-END:variables
}
