/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package capaPresentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author byron
 */
public class admSanciones extends javax.swing.JPanel {

    /**
     * Creates new form admSanciones
     */
    public admSanciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        comboEmp = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnDetalle = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        radioLeve = new javax.swing.JRadioButton();
        radioSeria = new javax.swing.JRadioButton();
        radioGrave = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dateTramite = new datechooser.beans.DateChooserCombo();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        comboDepto = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Empleado:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        comboEmp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 28, 238, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion General", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel5.setText("Empleado:");

        jLabel6.setText("ID:");

        jLabel7.setText("Cargo:");

        jLabel8.setText("Departamento:");

        jLabel1.setText("Numero de Faltas anteriores:");

        btnDetalle.setText("Detalles de Faltas");
        btnDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(btnDetalle)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnDetalle)
                .addGap(32, 32, 32))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 470, 280));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gravedad", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radioLeve.setText("Leve");
        jPanel2.add(radioLeve, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 28, -1, -1));

        radioSeria.setText("Seria");
        radioSeria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSeriaActionPerformed(evt);
            }
        });
        jPanel2.add(radioSeria, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 60, -1, -1));

        radioGrave.setText("Grave");
        jPanel2.add(radioGrave, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 92, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 440, 130));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripcion"));

        jScrollPane1.setViewportView(txtDesc);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 940, 170));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalles", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Fecha de tramite:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 131, -1, -1));

        dateTramite.setCalendarPreferredSize(new java.awt.Dimension(222, 159));
        try {
            dateTramite.setDefaultPeriods(new datechooser.model.multiple.PeriodSet());
        } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
            e1.printStackTrace();
        }
        jPanel4.add(dateTramite, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 56, -1, -1));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 440, -1));

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, -1, -1));

        jLabel9.setText("Departamento:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        comboDepto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 28, 238, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void radioSeriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSeriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioSeriaActionPerformed

    private void btnDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalleActionPerformed
        if(comboDepto.getSelectedIndex() != -1 && comboEmp.getSelectedIndex() != -1){
            // DETAIL'S CODE
        } else
            JOptionPane.showMessageDialog(null, "Seleccion un empleado", "¡Error!", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnDetalleActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(comboDepto.getSelectedIndex() != -1 && comboEmp.getSelectedIndex() != -1 && 
                (radioLeve.isSelected() || radioSeria.isSelected() || radioGrave.isSelected()) && dateTramite.getSelectedDate() != null && !txtDesc.getText().isEmpty()){
            // SAVE CODE
        } else
            JOptionPane.showMessageDialog(null, "Seleccione empleado, gravedad, fecha e ingrese descripción", "¡Error!", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalle;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox comboDepto;
    private javax.swing.JComboBox comboEmp;
    private datechooser.beans.DateChooserCombo dateTramite;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioGrave;
    private javax.swing.JRadioButton radioLeve;
    private javax.swing.JRadioButton radioSeria;
    private javax.swing.JTextPane txtDesc;
    // End of variables declaration//GEN-END:variables
}
