/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package capaPresentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author byron
 */
public class admViaticos extends javax.swing.JPanel {

    /**
     * Creates new form admViaticos
     */
    public admViaticos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboDep = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        txtOtros = new javax.swing.JFormattedTextField();
        txtAlim = new javax.swing.JFormattedTextField();
        txtHos = new javax.swing.JFormattedTextField();
        txtTrans = new javax.swing.JFormattedTextField();
        txtDias = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        comboAut = new javax.swing.JComboBox();
        dateSolic = new datechooser.beans.DateChooserCombo();
        btnSave = new javax.swing.JButton();
        comboEmp = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion General"));

        jLabel2.setText("Empleado:");

        jLabel3.setText("Cargo:");

        jLabel4.setText("Departamento:");

        jLabel5.setText("ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addContainerGap(912, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1050, -1));

        jLabel1.setText("Departamento:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 24, -1, -1));

        comboDep.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 21, 230, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Costos de Viaticos"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Alimentación:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel7.setText("Hospedaje:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel8.setText("Transporte:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel9.setText("Otros:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel10.setText("Días:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 38, -1, -1));

        jLabel11.setText("Total :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 38, -1, -1));

        labelTotal.setText("jLabel12");
        jPanel2.add(labelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 38, -1, -1));

        jLabel13.setText("Descripción:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 80, -1, -1));

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane1.setViewportView(txtDesc);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 107, 310, 100));
        jPanel2.add(txtOtros, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 168, 110, -1));
        jPanel2.add(txtAlim, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 48, 110, -1));
        jPanel2.add(txtHos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 88, 110, -1));
        jPanel2.add(txtTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 128, 110, -1));
        jPanel2.add(txtDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 36, 70, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 630, 230));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles de Viaticos"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("Fecha de Solicitud");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 49, -1, -1));

        jLabel15.setText("Autorizado por:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 111, -1, -1));

        comboAut.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(comboAut, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 108, 217, -1));

        dateSolic.setCalendarPreferredSize(new java.awt.Dimension(222, 159));
        try {
            dateSolic.setDefaultPeriods(new datechooser.model.multiple.PeriodSet());
        } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
            e1.printStackTrace();
        }
        jPanel3.add(dateSolic, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 48, -1, -1));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 410, 230));

        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, -1, -1));

        comboEmp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 21, 300, -1));

        jLabel16.setText("Empleado:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 24, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(comboEmp.getSelectedIndex() != -1 && 
                (!txtAlim.getText().isEmpty() || !txtHos.getText().isEmpty() || !txtTrans.getText().isEmpty() || !txtOtros.getText().isEmpty()) && 
                !txtDias.getText().isEmpty() && !txtDesc.getText().isEmpty() && dateSolic.getSelectedDate() != null && comboAut.getSelectedIndex() != -1){
            /// CODIGO GUARDAR
        } else
            JOptionPane.showMessageDialog(null, "Seleccione un empleado e ingrese al menos un costo, # días, descripción, fecha y persona que autoriza", "¡Error!", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox comboAut;
    private javax.swing.JComboBox comboDep;
    private javax.swing.JComboBox comboEmp;
    private datechooser.beans.DateChooserCombo dateSolic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JFormattedTextField txtAlim;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JFormattedTextField txtDias;
    private javax.swing.JFormattedTextField txtHos;
    private javax.swing.JFormattedTextField txtOtros;
    private javax.swing.JFormattedTextField txtTrans;
    // End of variables declaration//GEN-END:variables
}
