/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package capaPresentacion;

import encapsulacion.cargo;
import encapsulacion.funcionesCargo;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logicaNegocio.exceptionClass;
import logicaNegocio.logicaCargo;

/**
 *
 * @author byron
 */
public class crearCargo extends javax.swing.JFrame {

    DefaultTableModel modOb;
    /**
     * Creates new form crearCargo
     */
    public crearCargo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nombreCargo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desCargo = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        cargoFuncion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaFunciones = new javax.swing.JTable();
        agregarObj = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        salmin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        salmax = new javax.swing.JTextField();
        guardarCargo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Nombre del Puesto:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 32, -1, -1));
        jPanel1.add(nombreCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 32, 302, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripcion"));

        desCargo.setColumns(20);
        desCargo.setRows(5);
        jScrollPane1.setViewportView(desCargo);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 135, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Objetivos"));

        jLabel2.setText("Funcion:");

        tablaFunciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Funcion"
            }
        ));
        jScrollPane2.setViewportView(tablaFunciones);

        agregarObj.setText("Agregar");
        agregarObj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarObjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cargoFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(agregarObj)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargoFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarObj)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 264, -1, -1));

        jLabel5.setText("Salario Minimo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 81, -1, -1));
        jPanel1.add(salmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 78, 84, -1));

        jLabel6.setText("Salario Maximo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 81, -1, -1));
        jPanel1.add(salmax, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 78, 75, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        guardarCargo.setText("Guardar");
        guardarCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarCargoActionPerformed(evt);
            }
        });
        getContentPane().add(guardarCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void agregarObjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarObjActionPerformed
        if(!cargoFuncion.getText().isEmpty()){
            modOb=(DefaultTableModel)tablaFunciones.getModel();
            modOb.addRow(new Object[]{cargoFuncion.getText()});
            cargoFuncion.setText("");
        } else
            JOptionPane.showMessageDialog(null,"Ingrese función","¡Error!",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_agregarObjActionPerformed

    private void guardarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCargoActionPerformed
        modOb=(DefaultTableModel)tablaFunciones.getModel();
        
        if(modOb.getRowCount() > 0 && !salmin.getText().isEmpty() && !salmax.getText().isEmpty() && !nombreCargo.getText().isEmpty()){
            cargo puesto=new cargo();
            logicaCargo logDep= new logicaCargo();
            Set <funcionesCargo> funcionCargo=new HashSet<funcionesCargo>();
            
            try{

                puesto.setNombre(nombreCargo.getText());
                puesto.setDescripcion(desCargo.getText());
                puesto.setSalMin(Double.parseDouble(salmin.getText()));
                puesto.setSalMax(Double.parseDouble(salmax.getText()));

                for(int fila=0;fila<modOb.getRowCount();fila++){ //recorro las filas
                    funcionesCargo funcion=new funcionesCargo();
                    funcion.setTarea(modOb.getValueAt(fila,0).toString());
                    funcionCargo.add(funcion);
                }
                puesto.setFunciones(funcionCargo);
                logDep.validar(puesto);
                logDep.agregarDepartamento(puesto);

            } catch(exceptionClass ex){
                JOptionPane.showMessageDialog(null,ex.getError(),"!Error¡",JOptionPane.ERROR_MESSAGE);
            }
        } else
            JOptionPane.showMessageDialog(null,"Ingrese nombre de cargo, salario máximo, salario mínimo y al menos una función","¡Error!",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_guardarCargoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crearCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crearCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crearCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crearCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crearCargo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarObj;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JTextField cargoFuncion;
    private javax.swing.JTextArea desCargo;
    private javax.swing.JButton guardarCargo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nombreCargo;
    private javax.swing.JTextField salmax;
    private javax.swing.JTextField salmin;
    private javax.swing.JTable tablaFunciones;
    // End of variables declaration//GEN-END:variables
}
